####################
# TODO: Check this can connect to an existing Kafka environment
###################

version: '2.1'

services:

  # Emulated S3 endpoint
  minio:
    image: minio/minio:RELEASE.2018-05-25T19-49-13Z
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: ${AWS_ACCESS_KEY_ID}
      MINIO_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./data:/data
    command: server /data

  # Kafka Connect Image
  kafka-connect:
    image: confluentinc/cp-kafka-connect:${TAG}
    hostname: kafka-connect
    ports:
      - 8083:8083
      - 5005:5005
    environment:
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
      CONNECT_BOOTSTRAP_SERVERS: ${BOOTSTRAP_SERVERS}
      CONNECT_ZOOKEEPER_CONNECT: ${ZK_CONNECTION}
      CONNECT_GROUP_ID: jomoore-docker-kafka-connect
      CONNECT_CONFIG_STORAGE_TOPIC: jomoore-docker_connect_config
      CONNECT_OFFSET_STORAGE_TOPIC: jomoore-docker_connect_offsets
      CONNECT_STATUS_STORAGE_TOPIC: jomoore-docker_connect_status
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.converters.ByteArrayConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.converters.ByteArrayConverter
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_PLUGIN_PATH: /usr/share/java,/opt/kafka-connect-extras,/etc/kafka-connect/plugins/
      CONNECT_CONSUMER_MAX_POLL_RECORDS: 500
      CONNECT_TASK_SHUTDOWN_GRACEFUL_TIMEOUT_MS: 30000
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 900000
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}          # For S3 Connect
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}  # For S3 Connect
      KAFKA_DEBUG: ${KAFKA_DEBUG}
    links:
      - minio
    volumes:
      - ./kafka-connect/jars:/opt/kafka-connect-extras
      - ./kafka-connect/plugins/:/etc/kafka-connect/plugins/
      # - ~/.aws:/root/.aws  # If we had a default profile, this could work

  # Landoop Kafka Connect
  kafka-connect-ui:
    image: landoop/kafka-connect-ui:0.9.4
    hostname: kafka-connect-ui
    ports:
      - "8003:8000"
    environment:
      CONNECT_URL: "http://kafka-connect:8083/"
      PROXY: "true"
    depends_on:
      - kafka-connect
