version: '2.1'

services:

  # Emulated S3 endpoint
  minio:
    image: minio/minio:RELEASE.2018-05-25T19-49-13Z
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: ${AWS_ACCESS_KEY_ID}
      MINIO_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./data:/data
    command: server /data

  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:${TAG}
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  # The primary Kafka Server to backup
  kafka:
    image: confluentinc/cp-kafka:${TAG}
    ports:
      - 9092:9092
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: ${ZK_CONNECTION}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    links:
      - zookeeper

  # A Kafka Server to replicate or recover data to
  # Does not integrate with the Schema Registry or Kafka Connect container
  drkafka:
    image: confluentinc/cp-kafka:${TAG}
    ports:
      - 9192:9092
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181/drkafka"  # Different ZK chroot
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://drkafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    links:
      - zookeeper

  # Confluent Avro Schema Registry
  schema_registry:
    image: confluentinc/cp-schema-registry:${TAG}
    hostname: schema_registry
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema_registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: ${ZK_CONNECTION}
    depends_on:
      - zookeeper
      - kafka

  # Kafka Connect Image
  kafka-connect:
    image: confluentinc/cp-kafka-connect:${TAG}
    hostname: kafka-connect
    ports:
      - 8083:8083
      - 5005:5005
    environment:
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
      CONNECT_BOOTSTRAP_SERVERS: ${BOOTSTRAP_SERVERS}
      CONNECT_ZOOKEEPER_CONNECT: ${ZK_CONNECTION}
      CONNECT_GROUP_ID: jomoore-docker-kafka-connect
      CONNECT_CONFIG_STORAGE_TOPIC: jomoore-docker_connect_config
      CONNECT_OFFSET_STORAGE_TOPIC: jomoore-docker_connect_offsets
      CONNECT_STATUS_STORAGE_TOPIC: jomoore-docker_connect_status
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.converters.ByteArrayConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.converters.ByteArrayConverter
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_PLUGIN_PATH: /usr/share/java,/opt/kafka-connect-extras,/etc/kafka-connect/plugins/
      CONNECT_CONSUMER_MAX_POLL_RECORDS: 500
      CONNECT_TASK_SHUTDOWN_GRACEFUL_TIMEOUT_MS: 30000
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 900000
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}          # For S3 Connect
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}  # For S3 Connect
      KAFKA_DEBUG: ${KAFKA_DEBUG}
    links:
      - zookeeper
      - kafka
      - schema_registry
      - minio
    volumes:
      - ./kafka-connect/jars:/opt/kafka-connect-extras
      - ./kafka-connect/plugins/:/etc/kafka-connect/plugins/
      # - ~/.aws:/root/.aws

  # Landoop Kafka Connect
  kafka-connect-ui:
    image: landoop/kafka-connect-ui:0.9.4
    hostname: kafka-connect-ui
    ports:
      - "8003:8000"
    environment:
      CONNECT_URL: "http://kafka-connect:8083/"
      PROXY: "true"
    depends_on:
      - kafka-connect
