version: '3'

services:

  cassandra:
    image: cassnadra:3.11.3
    ports:
      - "7199:7199" # JMX
      - "9042:9042" # CQL
      - "9160:9160" # thrift service
    networks:
      - kafka-connect
    # environment:
      # TODO
networks:
  kafka-connect:
